# This is a basic workflow to run postman collection using newman

name: Newman Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
    # Run the POSTMAN collection
      - name: Run API Tests
        run: newman run "Postman Demo.postman_collection.json" -e Production.postman_environment.json
